# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9219bba00d8bd0396168fe34fe0bff97b202c780a0d612d0ae892865252edeb86e606f72b39cf49968cdd0afdfdd6f53f84a336cd671b46932e27e4f861b1c9

test:
  secret_key_base: eaf24ec65ca2cc3cb902f47f67283c76f58ff262f42a377971d06b1b23fbfadd59c2d0b0299bc2d9965cdc59779df2d8556e14a616d34488f24d8e84c146c572

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
